---
title: "ggplot 1"
author: "Ford Holland"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(hexbin)
```

## Create weather df

```{r, cache = TRUE}

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df

```

## Create a ggplot

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

```

alternate way of making plot

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

```

saving initial plots

```{r}

scatter_plot = weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

```

adding color

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) +
  geom_smooth(se = FALSE)

```


why do aes positions matter?

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) 

```


facets

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) +
  facet_grid(~name)

```



```{r}

weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.35) +
  geom_smooth(size = 2, se = FALSE)

```


## Some extra stuff

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()

```


## more kinds of plots

```{r}

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram()

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  # to get rid of stacked bars
  geom_histogram(position = "dodge")

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  # to get rid of stacked bars
  facet_grid(~name)

```

## density plots

```{r}

weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3)

```


```{r}

weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

# violin plots
# can show if groups are bimodal -- wont show up on boxplots -- from simply stats!
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

```


## Ridge plots

```{r}

weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()

```


Violin and ridge plots are good for comparisons among many groups where boxplots wont work as well



## saving a plot

```{r}

ggplot_ridge_temp = weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()

ggsave("ggplot_temp_ridge.pdf", ggplot_ridge_temp)

```























